version: "3.6"
services:
    app:
        image: wordpress:php7.3-fpm-alpine
        depends_on:
            - db
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_HOST=db:3306
            - WORDPRESS_DB_NAME=${DB_NAME}
            - WORDPRESS_DB_USER=${DB_USER}
            - WORDPRESS_DB_PASSWORD=${DB_PASS}
            - TZ=${TZ}
    web:
        image: nginx:1.17-alpine
        depends_on:
            - app
        ports:
            - 20080:80
        volumes:
            - ./logs:/var/log/nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./wordpress:/var/www/html
    db:
        image: mysql:8.0
        ports:
            - 23306:3306
        volumes:
            - db-store:/var/lib/mysql
            - ./logs:/var/log/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - TZ=${TZ}
volumes:
    db-store: